domain_path: C:\Users\twpin\prj\fpga\mms\tmc\vitis_ws\tmc_testbench\export\tmc_testbench\sw\standalone_microblaze_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
